### ISSUE TITLE
DS::FileStream::atEof() UB

### ISSUE THREAD

**Issue by Hoikas** [H-uru/dirtsand#185]
`DS::FileStream::atEof()` relies on undefined behavior if the file is opened in read mode. It basically tests for EOF by trying to read a character from the file and [put the character back](https://en.cppreference.com/w/c/io/fputc) for future read attempts. In Ubuntu 20.04 on WSL2, this causes the character read by atEof() to be discarded. This is also true for Alpine running in a docker container on WSL2.

**Comment by dpogue** [comment]
It sounds like using `ungetc` (rather than `fputc`) is the correct solution here?
