### ISSUE TITLE
Games manager unimplemented

### ISSUE THREAD

**Issue by branan** [H-uru/dirtsand#23]
The games manager is unimplemented. This breaks (at least):
- Heek
- Delin/Tsogal cloths
- Pellet scores

**Comment by Hoikas** [comment]
In the wake of H-uru/Plasma#516, which removes the game manager from the Plasma client, this should probably be closed.

**Comment by Deledrius** [comment]
I concur.

**Comment by branan** [comment]
🔥🔥🔥🔥🔥🔥🔥
